all:
	g++ hwlang_linux.cpp -o hwlang
install:
	sudo cp hwlang /usr/local/bin/hwlang
	sudo chmod +x /usr/local/bin/hwlang
	@echo "HWLang установлен. Теперь просто напиши 'hwlang' в терминале."
uninstall:
	sudo rm /usr/local/bin/hwlang
	@echo "HWLang удален."